### PR TITLE
Fix time, other small tweaks

### PR DESCRIPTION
**Pull request by Mashintime**
- Show date and times converted to local time zone
- Don't draw line if distance == 0
- Filter heard station list if base callsign and grid square are the same

### CODE REVIEW

**Comment by Mashintime** [comment]
I did it again, dang it.  Sorry for all the spacing.

**Comment by DJ2LS** [comment]
@Mashintime this needs an update, the code prettifier caused a merging problem. Sorry!

**Comment by DJ2LS** [comment]
@Mashintime I resolved the issues, should no working fine. As soon as you're ready we can merge it

**Comment by DJ2LS** [comment]
@Mashintime no, sorry. My fault. Its broken. Could you have a look at this?

**Comment by Mashintime** [comment]
Standby I pasted the wrong version in my re-commit.

**Comment by Mashintime** [comment]
Should be good to go now.

**Review by DJ2LS — APPROVED** [review]

**Pull request merged**
